# Generated by Django 5.1.3 on 2025-01-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_downvotes_remove_post_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='total_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
